package generate

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"path/filepath"
)

func DumpAst(output io.Writer, inputFileSpecs []string) error {
	fs := token.NewFileSet()
	for _, f := range inputFileSpecs {
		astFile, err := parser.ParseFile(fs, f, nil, parser.ParseComments)
		if err != nil {
			return err
		}
		ast.Print(fs, astFile)
	}
	return nil
}

func GenerateTypeScript(output io.Writer, inputFileSpecs []string) error {

	fmt.Fprintf(output, "// Generated by github.com/exponent-io/gots\n\n")
	for _, fs := range inputFileSpecs {
		err := processFile(fs, output)
		if err != nil {
			return err
		}
	}

	return nil
}

func processFile(filename string, w io.Writer) error {

	fs := token.NewFileSet()

	files, err := filepath.Glob(filename)
	if err != nil {
		return err
	}

	for _, f := range files {
		astFile, err := parser.ParseFile(fs, f, nil, parser.ParseComments)
		if err != nil {
			return err
		}
		writeConst(w, fs, astFile)
		writeStruct(w, fs, astFile)
	}
	return nil
}
