package generate

import (
	"fmt"
	"go/parser"
	"go/token"
	"io"
)

func GenerateTypeScript(output io.Writer, inputFileSpecs []string) error {

	fmt.Fprintf(output, "// Generated by github.com/exponent-io/gots\n\n")
	for _, fs := range inputFileSpecs {
		err := processFile(fs, output)
		if err != nil {
			return err
		}
	}

	return nil
}

func processFile(filename string, w io.Writer) error {

	fs := token.NewFileSet()

	astFile, err := parser.ParseFile(fs, filename, nil, parser.ParseComments)
	if err != nil {
		return err
	}

	writeStruct(w, fs, astFile)

	return nil
}
