package generate

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"path/filepath"
)

func DumpAst(output io.Writer, inputFileSpecs []string) error {
	fs := token.NewFileSet()
	for _, f := range inputFileSpecs {
		astFile, err := parser.ParseFile(fs, f, nil, parser.ParseComments)
		if err != nil {
			return err
		}
		ast.Print(fs, astFile)
	}
	return nil
}

func GenerateTypeScript(output io.Writer, inputFileSpecs []string) error {

	fmt.Fprintf(output, "// Generated by github.com/exponent-io/gots\n\n")
	for _, fs := range inputFileSpecs {
		err := processFileTypeScript(fs, output)
		if err != nil {
			return err
		}
	}

	return nil
}

func processFileTypeScript(filename string, w io.Writer) error {

	fs := token.NewFileSet()

	files, err := filepath.Glob(filename)
	if err != nil {
		return err
	}

	for _, f := range files {
		astFile, err := parser.ParseFile(fs, f, nil, parser.ParseComments)
		if err != nil {
			return err
		}
		writeConst(w, fs, astFile)
		writeStruct(w, fs, astFile)
	}
	return nil
}

func GenerateReflectTable(output io.Writer, pkg string, inputFileSpecs []string) error {

	fmt.Fprintf(output, "// Generated by github.com/exponent-io/gots\npackage %s\n\n", pkg)
	fmt.Fprintf(output, "type CreateType func() interface{}\n\n")
	fmt.Fprintf(output, "var TypeTable map[string]CreateType = map[string]CreateType{\n")
	for _, fs := range inputFileSpecs {
		err := processFileReflectTable(fs, output)
		if err != nil {
			return err
		}
	}
	fmt.Fprintf(output, "}\n")

	return nil
}

func processFileReflectTable(filename string, w io.Writer) error {

	fs := token.NewFileSet()

	files, err := filepath.Glob(filename)
	if err != nil {
		return err
	}

	for _, f := range files {
		astFile, err := parser.ParseFile(fs, f, nil, parser.ParseComments)
		if err != nil {
			return err
		}
		writeReflectLine(w, fs, astFile)
	}
	return nil
}
