// Generated by github.com/exponent-io/gots

// testfiles/sample.go:25:1
export type ItemValue = string;

export const ItemA:ItemValue = "A";
export const ItemB:ItemValue = "B";
export const ItemC:ItemValue = "C";

// testfiles/sample.go:33:1
export type OtherValue = string;

export const OtherItem:OtherValue = "Other";

// testfiles/sample.go:35:1

export const StringVal:string = "string";

// testfiles/sample.go:3:6
export interface App {
  id:    string; // Id
  title: string; // Title
  url?:  string; // Url
  Hours: number; // Hours
}

// testfiles/sample.go:11:6
export interface Table {
  name:     string;   // Name
  columns?: Column[]; // Columns
}

// testfiles/sample.go:18:6
export interface Column {
  name: string; // Name
  type: string; // Type
}

