// Generated by github.com/exponent-io/gots

// testfiles/sample.go:34:1
export type ItemValue = string;

export const ItemA:ItemValue = "A";
export const ItemB:ItemValue = "B";
export const ItemC:ItemValue = "C";

// testfiles/sample.go:42:1
export type OtherValue = string;

export const OtherItem:OtherValue = "Other";

// testfiles/sample.go:44:1

export const StringVal:string = "string";

// testfiles/sample.go:8:6
export interface App {
  id:     string;     // Id
  title:  string;     // Title
  url?:   string;     // Url
  Hours:  number;     // Hours
  config: any;        // Config
  exten:  any;        // Extend
  blob:   Uint8Array; // Blob
}

// testfiles/sample.go:19:6
export interface Table {
  name:     string;   // Name
  columns?: Column[]; // Columns
  created:  string;   // Created
}

// testfiles/sample.go:27:6
export interface Column {
  name: string; // Name
  type: string; // Type
}

