// Generated by github.com/exponent-io/gots

// testfiles/sample.go:3:6
export interface App {
  id:    string; // Id
  title: string; // Title
  url?:  string; // Url
  Hours: number; // Hours
}

// testfiles/sample.go:11:6
export interface Table {
  name:     string;   // Name
  columns?: Column[]; // Columns
}

// testfiles/sample.go:18:6
export interface Column {
  name: string; // Name
  type: string; // Type
}

